### PR TITLE
Support Swift 1.2

### PR DESCRIPTION
**Pull request by kylef**
This adds support for the breaking Swift changes in Swift 1.2 language release last Friday.

Notes on changes for this unfamiliar with Swift:
- Changes to use the newer modern compact dictionary definition syntax.
  
  ``` diff
  - Dictionary<String, AnyObject>
  + [String:AnyObject]
  ```
- Changes to how optional values are unwrapped
  - `property.value as! String`
  - `property.value as? String`
- Removes the Alamofire extension completely.
  It doesn't make sense to keep the Alamofire extension considering Hyperdrive should be used in favour of this extension.
  I'm removing it in this pull request as it would take much more work to make the dependencies work for Swift 1.2 requiring changing how dependencies are integrated.
- Removes the use of Travis CI, they do not support Swift 1.2 and will result in build failures.

### CODE REVIEW

**Comment by zdne** [comment]
@kylef any other CI in place of Travis?

**Comment by kylef** [comment]
@zdne There are no CIs that support Swift 1.2 from what I understand.

**Comment by zdne** [comment]
@kylef well, that is not fortunate. Was anything pushing this change?

**Comment by kylef** [comment]
@zdne It's mostly due to everyone moves to the latest Swift quickly. We should support the latest otherwise people will be unable to use this framework in the current version of Xcode 6.3.

Most people have either complained my other frameworks don't work or asked for Swift 1.2 support before the gold master of Xcode 6.3 was out on Friday but during the betas of Xcode.
- https://github.com/kylef/Mockingjay/issues/16
- https://github.com/kylef/URITemplate.swift/issues/11
- https://github.com/QueryKit/QueryKit/issues/26
- https://github.com/kylef/WebLinking.swift/pull/1

Since it's used in Hyperdrive, it would be required to make that work with the current version of Swift/Xcode.

**Comment by zdne** [comment]
:+1: Ok thanks for the explanation!

**Pull request merged**
